name: Checkout

on:
  workflow_call:
    inputs:
      wfcmd:
        required: true
        type: string

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.4
        with:
          fetch-depth: '0'
      - name: Run wfcmd
        run: |
          echo "${{ inputs.config-path }}"
          ${{ inputs.config-path }}

