name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Group
        run: |
          echo "##[group]title"
          echo "contents"
          echo "##[endgroup]"
          echo "outside"
          echo "##[group]"
          echo "content2"
          echo "##[endgroup]"

      - name: Set Vars
        run: |
          for NUM in 1 2 3 4 5
          do
            echo "VARIABLE=BLAH${NUM}" >> $GITHUB_ENV
            echo "BLAH${NUM}=BLAHBLAH${NUM}" >> $GITHUB_ENV
            echo ${{ env[env.VARIABLE] }}
          done

      - name: Test Vars
        run: |
          for NUM in 1 2 3 4 5
          do
            echo "VARIABLE=BLAH${NUM}" >> $GITHUB_ENV
            echo ${{ env[env.VARIABLE] }}
          done
